name: lab_10
description: A new Flutter project

environment:
  sdk: '^3.9.0'

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/kimep_logo.png

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.8
  flutter_bloc: ^8.1.3
  dio: ^5.7.0
  retrofit: ^4.4.0
  json_annotation: ^4.9.0

  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  shared_preferences: ^2.3.2
  google_maps_flutter: ^2.7.0
  mobile_scanner: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0
